server:
  port: 8080

#model: gpt-4 #not working?
model: gpt-3.5-turbo

timezone: +2

spring:
  application:
    name: openai
  config:
#    import: "aws-parameterstore:/"  #root level in Systems Manager Parameter Store
    import: "aws-parameterstore:/config/openai/" #last slash is crucial for directories

logging.level.com.amazonaws.request: DEBUG