server:
  port: 8081

spring:
  application:
    name: openai
  config:
#    import: "aws-parameterstore:/"  #root level in Systems Manager Parameter Store
    import: "aws-parameterstore:/config/openai/" #last slash is crucial for directories

logging.level.com.amazonaws.request: DEBUG